// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyoqbpjjjrczrulfjnks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5b3FicGpqanJjenJ1bGZqbmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDcwODMsImV4cCI6MjA1ODgyMzA4M30.X-zwY3zy5-Pt4AzTkvaxNO2ANTy49ytcqS2me0_n9CQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);